name: BitBetter Image

on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  regenerate_cert:
    runs-on: ubuntu-latest
    name: Regenerate Certificate
    outputs:
      regenerate: ${{ steps.check_regenerate.outputs.regenerate }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if Regeneration Requested
        id: check_regenerate
        run: |
          export REGENERATE="$(cat regenerate_cert.txt)"
          echo "regenerate=$REGENERATE" >> $GITHUB_OUTPUT
      - name: Regenerate Certificate
        id: regenerate
        if: ${{ steps.check_regenerate.outputs.regenerate == 'true' }}
        run: |
          src/cert_gen/generate.sh
          echo false > regenerate_cert.txt
          git config user.name alexyao2015
          git config user.email alexyao2015@gmail.com
          git add .
          git commit -m "Regenerate Certificate"
          git push

  check_version:
    runs-on: ubuntu-latest
    name: Check Last Built Version
    outputs:
      buildimage: ${{ steps.get_version.outputs.buildimage }}
      buildversion: ${{ steps.get_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Version
        id: get_version
        run: |
          export BW_VERSION_LATEST="$(curl -sL "https://func.bitwarden.com/api/dl/?app=self-host&platform=linux" | grep '^COREVERSION=' | awk -F\" '/COREVERSION/{ print $2 }')"
          export BW_VERSION_LAST_BUILT="$(cat bw_version.txt)"
          if [ $BW_VERSION_LATEST == $BW_VERSION_LAST_BUILT ]; then
            export NEED_BUILD=false
          else
            export NEED_BUILD=true
          fi
          echo "buildimage=$NEED_BUILD" >> $GITHUB_OUTPUT
          echo "buildversion=$BW_VERSION_LATEST" >> $GITHUB_OUTPUT
          echo Build required: ${NEED_BUILD}
          echo Last build version: ${BW_VERSION_LAST_BUILT}
          echo Build version: ${BW_VERSION_LATEST}

  build_bitbetter:
    runs-on: ubuntu-latest
    name: Build BitBetter
    outputs:
      image_name: ${{ steps.set_var.outputs.image_name }}
      artifact_name: ${{ steps.set_var.outputs.artifact_name }}
    needs: [check_version, regenerate_cert]
    if: ${{ needs.check_version.outputs.buildimage == 'true' || needs.regenerate_cert.outputs.regenerate == 'true' || github.event_name == 'push' }}
    strategy:
      matrix:
        include:
          - target: bitbetter-api-public
            image_name: api
          - target: bitbetter-identity-public
            image_name: identity
          - target: bitbetter-licensegen-public
            image_name: licensegen

          - target: bitbetter-api-custom
            image_name: api-custom
          - target: bitbetter-identity-custom
            image_name: identity-custom
          - target: bitbetter-licensegen-custom
            image_name: licensegen-custom

          - target: bitbetter-certificate-gen
            image_name: certificate-gen
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true
      - name: Set Variables
        id: set_var
        run: |
          set -x
          artifact_name="ci-${{ matrix.image_name }}-${{ github.run_number }}"
          docker_image_name="bitbetter/${{ matrix.image_name }}:ci-${{ github.run_number }}"
          echo "artifact_name=${artifact_name}" >> $GITHUB_OUTPUT
          echo "docker_image_name=${docker_image_name}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          BW_VERSION=${{ needs.check_version.outputs.buildversion }} \
          IMAGE_BASE=bitbetter \
            docker buildx bake \
              --progress=plain \
              --metadata-file=metadata.json \
              ${{ matrix.target }}
          image_name=$(jq -r '.["${{ matrix.target }}"]["image.name"]' metadata.json)
          echo "Image built: ${image_name}"
          docker tag "${image_name}" "${{ steps.set_var.outputs.docker_image_name }}"
          echo "Image tagged: ${{ steps.set_var.outputs.docker_image_name }}"
      - name: Save tarball
        run: |
          docker save --output output.tar ${{ steps.set_var.outputs.docker_image_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_var.outputs.artifact_name }}.tar
          path: output.tar

  publish_bitbetter:
    runs-on: ubuntu-latest
    name: Publish BitBetter
    needs: [check_version, build_bitbetter]
    if: ${{ github.event_name == 'push' }}
    env:
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    strategy:
      matrix:
        registry:
          - {
              url: "https://index.docker.io/v1/",
              username: dockerID,
              password: dockerPassword,
              repo: yaoa/bitbetter,
            }
          - {
              url: ghcr.io/alexyao2015,
              username: CR_USER,
              password: CR_PAT,
              repo: ghcr.io/alexyao2015/bitbetter,
            }
        image_name:
          [
            api,
            identity,
            licensegen,
            api-custom,
            identity-custom,
            licensegen-custom,
            certificate-gen,
          ]

    steps:
      # just to improve readability
      - name: Set Variables
        id: set_var
        run: |
          export REPO=${{ matrix.registry.repo }}
          export IMAGE_NAME=${{ matrix.image_name }}

          echo "REPO=${REPO}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

          echo Repository set as: ${REPO}
          echo Image name set as: ${IMAGE_NAME}
      - name: Download container artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-${{ matrix.image_name }}-${{ github.run_number }}.tar
      - name: Import image
        run: |
          docker load --input output.tar
      - name: Login
        run: |
          docker login ${{ matrix.registry.url }} -u ${{ secrets[matrix.registry.username] }} -p ${{ secrets[matrix.registry.password] }}
      - name: Deploy Run Number
        run: |
          docker tag bitbetter/${IMAGE_NAME}:ci-${{ github.run_number }} ${REPO}:${IMAGE_NAME}-${{ github.run_number }}
          docker push ${REPO}:${IMAGE_NAME}-${{ github.run_number }}
          echo ${REPO}:${IMAGE_NAME}-${{ github.run_number }} Deployed
      - name: Deploy Latest
        run: |
          docker tag bitbetter/${IMAGE_NAME}:ci-${{ github.run_number }} ${REPO}:${IMAGE_NAME}-latest
          docker push ${REPO}:${IMAGE_NAME}-latest
          echo ${REPO}:${IMAGE_NAME}-latest Deployed
      - name: Deploy Tag
        run: |
          docker tag bitbetter/${IMAGE_NAME}:ci-${{ github.run_number }} ${REPO}:${IMAGE_NAME}-${VERSION}
          docker push ${REPO}:${IMAGE_NAME}-${VERSION}
          echo ${REPO}:${IMAGE_NAME}-${VERSION} Deployed

  commit_version:
    runs-on: ubuntu-latest
    name: Commit Build Version
    needs: [check_version, publish_bitbetter]
    env:
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v4
      # May fail if a push occurs but there is no new version to commit
      - name: Save Version Number
        continue-on-error: true
        run: |
          echo ${VERSION} > bw_version.txt
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Bitwarden Version Update"
          git push
