name: BitBetter Image

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  regenerate_cert:
    runs-on: ubuntu-latest
    name: Regenerate Certificate
    outputs:
      regenerate: ${{ steps.check_regenerate.outputs.regenerate }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Check if Regeneration Requested
        id: check_regenerate
        run: |
          export REGENERATE="$(cat regenerate_cert.txt)"
          echo "##[set-output name=regenerate;]$REGENERATE"
      - name: Regenerate Certificate
        id: regenerate
        if: ${{ steps.check_regenerate.outputs.regenerate == 'true' }}
        run: |
          docker build -f ./publicKeys/Dockerfile -t bitbetter/certificate-gen .
          docker run --rm -v $PWD/publicKeys:/certs bitbetter/certificate-gen
          echo false > regenerate_cert.txt
      - name: Commit New Certificate
        if: ${{ steps.check_regenerate.outputs.regenerate == 'true' }}
        uses: EndBug/add-and-commit@v4
        with:
          message: "Regenerate Certificate"
          add: "publicKeys/cert.pem publicKeys/key.pem publicKeys/cert.cert publicKeys/cert.pfx regenerate_cert.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_version:
    runs-on: ubuntu-latest
    name: Check Last Built Version
    outputs:
      buildimage: ${{ steps.get_version.outputs.buildimage }}
      buildversion: ${{ steps.get_version.outputs.buildversion }}
      dockerrepo: ${{ steps.set_repo.outputs.dockerrepo }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Get Latest Version
        id: get_version
        run: |
          export BW_VERSION_LATEST="$(curl --silent https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh | grep 'COREVERSION="' | sed 's/^[^"]*"//; s/".*//')"
          export BW_VERSION_LAST_BUILT="$(cat bw_version.txt)"
          if [ $BW_VERSION_LATEST == $BW_VERSION_LAST_BUILT ]; then
            export NEED_BUILD=false
          else
            export NEED_BUILD=true
          fi
          echo "##[set-output name=buildimage;]$NEED_BUILD"
          echo "##[set-output name=buildversion;]$BW_VERSION_LATEST"
      - name: Set Repo
        id: set_repo
        run: |
          export REPOSITORY=yaoa/bitbetter
          echo "##[set-output name=dockerrepo;]$REPOSITORY"

  build_bitbetter:
    runs-on: ubuntu-latest
    name: Publish BitBetter
    needs: [check_version, regenerate_cert]
    if: ${{ needs.check_version.outputs.buildimage == 'true' || needs.regenerate_cert.outputs.regenerate == 'true' || github.event_name == 'push' }}
    env:
      REPO: ${{ needs.check_version.outputs.dockerrepo }}
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/bitBetter/Dockerfile --build-arg BITWARDEN_TAG=bitwarden/api:${VERSION} -t bitbetter/ci:api .
          docker build -f ./src/bitBetter/Dockerfile --build-arg BITWARDEN_TAG=bitwarden/identity:${VERSION} -t bitbetter/ci:identity .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Run Number
        run: |
          docker tag bitbetter/ci:api ${REPO}:api-$GITHUB_RUN_NUMBER
          docker tag bitbetter/ci:identity ${REPO}:identity-$GITHUB_RUN_NUMBER
          docker push ${REPO}:api-$GITHUB_RUN_NUMBER
          docker push ${REPO}:identity-$GITHUB_RUN_NUMBER
          echo ${REPO}:api-$GITHUB_RUN_NUMBER Deployed
          echo ${REPO}:identity-$GITHUB_RUN_NUMBER Deployed
      - name: Deploy Latest
        run: |
          docker tag bitbetter/ci:api ${REPO}:api-latest
          docker tag bitbetter/ci:identity ${REPO}:identity-latest
          docker push ${REPO}:api-latest
          docker push ${REPO}:identity-latest
          echo ${REPO}:api-latest Deployed
          echo ${REPO}:identity-latest Deployed
      - name: Deploy Tag
        run: |
          docker tag bitbetter/ci:api ${REPO}:api-${VERSION}
          docker tag bitbetter/ci:identity ${REPO}:identity-${VERSION}
          docker push ${REPO}:api-${VERSION}
          docker push ${REPO}:identity-${VERSION}
          echo ${REPO}:api-${VERSION} Deployed
          echo ${REPO}:identity-${VERSION} Deployed
      - name: Save Version Number
        run: |
          echo ${VERSION} > bw_version.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Bitwarden Version Update"
          add: "bw_version.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_generator:
    runs-on: ubuntu-latest
    name: Publish License Generator
    needs: build_bitbetter
    env:
      REPO: ${{ needs.check_version.outputs.dockerrepo }}
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/licenseGen/Dockerfile --build-arg BITWARDEN_TAG=bitwarden/api:${VERSION} -t bitbetter/ci:licensegen .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Run Number
        run: |
          docker tag bitbetter/ci:licensegen ${REPO}:licensegen-$GITHUB_RUN_NUMBER
          docker push ${REPO}:licensegen-$GITHUB_RUN_NUMBER
          echo licensegen-$GITHUB_RUN_NUMBER Deployed
      - name: Deploy Latest
        run: |
          docker tag bitbetter/ci:licensegen ${REPO}:licensegen-latest
          docker push ${REPO}:licensegen-latest
          echo ${REPO}:licensegen-latest Deployed
      - name: Deploy Tag
        run: |
          docker tag bitbetter/ci:licensegen ${REPO}:licensegen-${VERSION}
          docker push ${REPO}:licensegen-${VERSION}
          echo ${REPO}:licensegen-${VERSION} Deployed
