name: BitBetter Custom Image

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  check_version:
    runs-on: ubuntu-latest
    name: Check Last Built Version
    outputs:
      buildimage: ${{ steps.get_version.outputs.buildimage }}
      buildversion: ${{ steps.get_version.outputs.buildversion }}
      dockerrepo: ${{ steps.set_repo.outputs.dockerrepo }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Get Latest Version
        id: get_version
        run: |
          export BW_VERSION_LATEST="$(curl --silent https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh | grep 'COREVERSION="' | sed 's/^[^"]*"//; s/".*//')"
          export BW_VERSION_LAST_BUILT="$(cat bw_version.txt)"
          if [ $BW_VERSION_LATEST == $BW_VERSION_LAST_BUILT ]; then
            export NEED_BUILD=false
          else
            export NEED_BUILD=true
          fi
          echo "##[set-output name=buildimage;]$NEED_BUILD"
          echo "##[set-output name=buildversion;]$BW_VERSION_LATEST"
      - name: Set Repo
        id: set_repo
        run: |
          export REPOSITORY=yaoa
          echo "##[set-output name=dockerrepo;]$REPOSITORY"

  build_bitbetter:
    runs-on: ubuntu-latest
    name: Publish BitBetter
    needs: check_version
    if: ${{ needs.check_version.outputs.buildimage == 'true' || github.event_name == 'push' }}
    env:
      REPO: ${{ needs.check_version.outputs.dockerrepo }}
      VERSION: ${{ needs.check_version.outputs.buildversion }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/bitBetter/Dockerfile.custom --build-arg BITWARDEN_TAG=bitwarden/api:${{ needs.check_version.outputs.buildversion }} -t ${REPO}/bitbetter:api .
          docker build -f ./src/bitBetter/Dockerfile.custom --build-arg BITWARDEN_TAG=bitwarden/identity:${{ needs.check_version.outputs.buildversion }} -t ${REPO}/bitbetter:identity .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Run Number
        run: |
          docker tag ${REPO}/bitbetter:api ${REPO}/bitbetter:api-custom-$GITHUB_RUN_NUMBER
          docker tag ${REPO}/bitbetter:identity ${REPO}/bitbetter:identity-custom-$GITHUB_RUN_NUMBER
          docker push ${REPO}/bitbetter:api-custom-$GITHUB_RUN_NUMBER
          docker push ${REPO}/bitbetter:identity-custom-$GITHUB_RUN_NUMBER
          echo ${REPO}/bitbetter:api-custom-$GITHUB_RUN_NUMBER Deployed
          echo ${REPO}/bitbetter:identity-custom-$GITHUB_RUN_NUMBER Deployed
      - name: Deploy Latest
        run: |
          docker tag ${REPO}/bitbetter:api ${REPO}/bitbetter:api-custom-latest
          docker tag ${REPO}/bitbetter:identity ${REPO}/bitbetter:identity-custom-latest
          docker push ${REPO}/bitbetter:api-custom-latest
          docker push ${REPO}/bitbetter:identity-custom-latest
          echo ${REPO}/bitbetter:api-custom-latest Deployed
          echo ${REPO}/bitbetter:identity-custom-latest Deployed
      - name: Deploy Tag
        run: |
          docker tag ${REPO}/bitbetter:api ${REPO}/bitbetter:api-custom-${VERSION}
          docker tag ${REPO}/bitbetter:identity ${REPO}/bitbetter:identity-custom-${VERSION}
          docker push ${REPO}/bitbetter:api-custom-${VERSION}
          docker push ${REPO}/bitbetter:identity-custom-${VERSION}
          echo ${REPO}/bitbetter:api-custom-${VERSION} Deployed
          echo ${REPO}/bitbetter:identity-custom-${VERSION} Deployed
      - name: Save Version Number
        run: |
          echo ${VERSION} > bw_version.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Bitwarden Version Update"
          add: "bw_version.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_lic_generator:
    runs-on: ubuntu-latest
    name: Publish License Generator
    needs: [check_version, build_bitbetter]
    env:
      REPO: ${{ needs.check_version.outputs.dockerrepo }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./src/licenseGen/Dockerfile.custom -t ${REPO}/bitbetter:licensegen .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Run Number
        run: |
          docker tag ${REPO}/bitbetter:licensegen ${REPO}/bitbetter:licensegen-custom-$GITHUB_RUN_NUMBER
          docker push ${REPO}/bitbetter:licensegen-custom-$GITHUB_RUN_NUMBER
          echo ${REPO}/bitbetter:licensegen-custom-$GITHUB_RUN_NUMBER Deployed
      - name: Deploy Latest
        run: |
          docker tag ${REPO}/bitbetter:licensegen ${REPO}/bitbetter:licensegen-custom-latest
          docker push ${REPO}/bitbetter:licensegen-custom-latest
          echo ${REPO}/bitbetter:licensegen-custom-latest Deployed
  
  build_cert_gen:
    runs-on: ubuntu-latest
    name: Publish Certificate Generator
    needs: [check_version, build_bitbetter]
    env:
      REPO: ${{ needs.check_version.outputs.dockerrepo }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'public'
      - name: Build Image
        id: build_image
        run: |
          docker build -f ./publicKeys/Dockerfile -t ${REPO}/bitbetter:certificate-gen .
      - name: Login
        run: |
          docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
      - name: Deploy Run Number
        run: |
          docker tag ${REPO}/bitbetter:certificate-gen ${REPO}/bitbetter:certificate-gen-$GITHUB_RUN_NUMBER
          docker push ${REPO}/bitbetter:certificate-gen-$GITHUB_RUN_NUMBER
          echo ${REPO}/bitbetter:certificate-gen-$GITHUB_RUN_NUMBER Deployed
      - name: Deploy Latest
        run: |
          docker tag ${REPO}/bitbetter:certificate-gen ${REPO}/bitbetter:certificate-gen-latest
          docker push ${REPO}/bitbetter:certificate-gen-latest
          echo ${REPO}/bitbetter:certificate-gen-latest Deployed